### ISSUE TITLE
csv files from tool sometimes open corrupted in Excel

### ISSUE THREAD

**Issue by andrewrfreed** [IBM/watson-stt-wer-python#12]
Accented characters in CSV sometimes appear corrupted by Excel.

It seems there is not a good hand-off between CSV writer and Excel, marking the file with UTF-8 encoding.

Related links from investigation:
* https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically
* https://tobywf.com/2017/08/unicode-csv-excel/
* https://stackoverflow.com/questions/5202648/adding-bom-unicode-signature-while-saving-file-in-python/47770748

**Comment by marconoel** [comment]
Code update included
