### ISSUE TITLE
Can u create a video demostration?

### ISSUE THREAD

**Issue by johnfelipe** [IBM/watson-stt-wer-python#2]

**Comment by andrewrfreed** [comment]
Hi @johnfelipe , please see https://youtu.be/yfiZLwOR2PA.
There will soon be a Medium article about the tool as well.

**Comment by marconoel** [comment]
@johnfelipe Here's the Medium article which includes a Youtube demo https://medium.com/@marconoel/new-python-scripts-to-measure-word-error-rate-on-watson-speech-to-text-77ecaa513f60
