### ISSUE TITLE
Add 'grid_search' feature

### ISSUE THREAD

**Issue by gus07ven** [IBM/watson-stt-wer-python#27]
Currently we can run experiments that test the STT model's sensitivity parameter. I'd like to run experiments over a range of parameters to see which combination of parameters provides the best results (similar to scikit-learn's grid_search but more basic: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html). Example values of parameters we could combine:

FLOAT_PARAMETERS = {'end_of_phrase_silence_time': [0.0, 100.0, 120.0],
                    'inactivity_timeout': [-1],
                    'speech_detector_sensitivity': [0.5, 0.7, 0.9, 1.0],
                    'background_audio_suppression': [0.0, 0.2, 0.5, 0.7]}

Sample flow:
a. Run experiment 1 with STT parameters of:
'end_of_phrase_silence_time'=0.0, 
'inactivity_timeout'=-1, 
'speech_detector_sensitivity'=0.5,
'background_audio_suppresion'=0.0
b. Store results of experiment 1
c. Run experiment 2 with STT parameters of:
'end_of_phrase_silence_time'=0.0, 
'inactivity_timeout'=-1, 
'speech_detector_sensitivity'=0.5,
'background_audio_suppresion'=0.2  <<<<<<<<<< only parameter changed.
d. Store results of experiment 2
e. Repeat for all possible combinations of parameters

For the FLOAT_PARAMETERS above there would be 48 total combinations:
[(0.0, -1, 0.5, 0.0), (0.0, -1, 0.5, 0.2), (0.0, -1, 0.5, 0.5), (0.0, -1, 0.5, 0.7), (0.0, -1, 0.7, 0.0), (0.0, -1, 0.7, 0.2),
  (0.0, -1, 0.7, 0.5), (0.0, -1, 0.7, 0.7), (0.0, -1, 0.9, 0.0), (0.0, -1, 0.9, 0.2), (0.0, -1, 0.9, 0.5), (0.0, -1, 0.9, 0.7),
  (0.0, -1, 1.0, 0.0), (0.0, -1, 1.0, 0.2), (0.0, -1, 1.0, 0.5), (0.0, -1, 1.0, 0.7), (100.0, -1, 0.5, 0.0), (100.0, -1, 0.5, 0.2),
  (100.0, -1, 0.5, 0.5), (100.0, -1, 0.5, 0.7), (100.0, -1, 0.7, 0.0), (100.0, -1, 0.7, 0.2), (100.0, -1, 0.7, 0.5), (100.0, -1, 0.7, 0.7),
  (100.0, -1, 0.9, 0.0), (100.0, -1, 0.9, 0.2), (100.0, -1, 0.9, 0.5), (100.0, -1, 0.9, 0.7), (100.0, -1, 1.0, 0.0), (100.0, -1, 1.0, 0.2),
  (100.0, -1, 1.0, 0.5), (100.0, -1, 1.0, 0.7), (120.0, -1, 0.5, 0.0), (120.0, -1, 0.5, 0.2), (120.0, -1, 0.5, 0.5), (120.0, -1, 0.5, 0.7),
  (120.0, -1, 0.7, 0.0), (120.0, -1, 0.7, 0.2), (120.0, -1, 0.7, 0.5), (120.0, -1, 0.7, 0.7), (120.0, -1, 0.9, 0.0), (120.0, -1, 0.9, 0.2),
  (120.0, -1, 0.9, 0.5), (120.0, -1, 0.9, 0.7), (120.0, -1, 1.0, 0.0), (120.0, -1, 1.0, 0.2), (120.0, -1, 1.0, 0.5), (120.0, -1, 1.0, 0.7)]

**Comment by marconoel** [comment]
Completed
