### ISSUE TITLE
SSL certificate error when running scripts

### ISSUE THREAD

**Issue by lmazzoli** [IBM/watson-stt-wer-python#28]
receiving an SSL Certificate error (CERTIFICATE_VERIFY_FAILED) when running the python scripts. Had to run commands to instruct Python to use the system certificate store. Would be good to add notes to the Readme file.

**_Windows_**
```
pip install --trusted-host pypi.org --trustedhost files.python.org python-certifi-win32
```

**_MacOS_**

Open a terminal Windows and change to the location of your python installation
```
cd /Applications/Python 3.6
./Install Certificates.command
```

**Comment by andrewrfreed** [comment]
Closed due to merge of #29
