### ISSUE TITLE
Tool not compatible with latest version of dependencies

### ISSUE THREAD

**Issue by lmazzoli** [IBM/watson-stt-wer-python#34]
the jiwer python module has had an update, and the latest version has breaking changes for this tool.  A quick fix is to specifically install version 2.2.0 of jiwer.

See this issue opened for the jiwer breaking change:  https://github.com/jitsi/jiwer/issues/54

**Comment by andrewrfreed** [comment]
I created a PR for a workaround - I prefer to leave this issue in place as we track a more permanent solution.  I've yet to get our code elegantly working with 2.2.0 and 2.3.0 at the same time, and have not been successful in many 2.3.0 refactorings either.
