### ISSUE TITLE
Enable stemming pre-processor as optional component

### ISSUE THREAD

**Issue by andrewrfreed** [IBM/watson-stt-wer-python#7]
Currently WER tool treats trivial differences as word errors, for instance the singular and plural form of a word are treated differently (ex: benefit vs benefits)

User should have option to evaluate w/ stemming in place, so they can ignore these differences.
In evaluation sheet, the "Transcription (clean)" and "Reference (clean)" columns will include the stemmed version, and the "Differences" column will include stemmed words only.

Background reference on stemming:
https://towardsdatascience.com/stemming-vs-lemmatization-2daddabcb221

Suggestion is to use Porter stemmer which is simplest to configure/execute and does not require language-specific customization.

cc @marconoel

**Comment by marconoel** [comment]
Feature included
