### ISSUE TITLE
Transcribing multiple audio files, each over 20 minutes long to get WER

### ISSUE THREAD

**Issue by akshayribm** [IBM/watson-stt-wer-python#82]
I have been trying to use the instructions to transcribe some audio files to get the WER. The audio files are over 20 minutes long so the reference dialog would be multiple paragraphs. I am struggling on how to get the reference dialog to use; this is also my first time using python code so any help would be appreciated.

**Comment by andrewrfreed** [comment]
A typical process for building a reference is to generate a machine transcription and then correct it.  You are correct, the transcript will be lengthy, and you may need to figure on 6x time of audio to correct it (2 hours for a 20 minute audio).

The `transcribe.py` script should be able to generate the transcription that you can then correct into a reference.  The reference is not required at time of transcription (it is optional parameter).

1) Use `transcribe.py` to generate the transcript
2) Manually correct the transcript, add to a reference file
3) Use the `analyze.py` to get word error rate, etc.

If you get errors, please post them here.
